# Generated by Django 3.1.7 on 2022-01-18 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_departamento', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='COD_DANE')),
                ('nombre_departamento', models.CharField(max_length=60, verbose_name='Nombre Departamento')),
                ('id_area', models.CharField(max_length=10, verbose_name='ID Area')),
                ('nombre_area', models.CharField(max_length=500, verbose_name='Nombre Area')),
                ('area_ha', models.FloatField(verbose_name='Area Ha')),
            ],
            options={
                'ordering': ['id_area'],
            },
        ),
    ]
